spring:
  http:
    clients:
      connect-timeout: 3s
      read-timeout: 5s
  datasource:
    url: jdbc:postgresql://localhost:5433/articles
    username: articles
    password: articles
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

articles:
  client:
    base-url: https://jsonplaceholder.typicode.com
  fetch:
    initial-delay: 10s
    delay: 5m