spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/articles
    username: articles
    password: articles
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

articles:
  client:
    base-url: https://jsonplaceholder.typicode.com
    connection-time-out: 3s
    read-time-out: 5s